// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvvN6hD_8ScmribHSYOcFG8fM5A39Gxrc',
    appId: '1:766035577642:web:d3b26c6d4ad1fa1548ac53',
    messagingSenderId: '766035577642',
    projectId: 'fashionhub-da9d7',
    authDomain: 'fashionhub-da9d7.firebaseapp.com',
    storageBucket: 'fashionhub-da9d7.appspot.com',
    measurementId: 'G-1K7E4GJKVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL-X0WTcu_RUm0Di09__RR_pFb8GADpxA',
    appId: '1:766035577642:android:c753f6b3f940597e48ac53',
    messagingSenderId: '766035577642',
    projectId: 'fashionhub-da9d7',
    storageBucket: 'fashionhub-da9d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBypu2Vt8W_KeS3-Ac-GV1hXQh7fC5eZY4',
    appId: '1:766035577642:ios:a8e6a2b8124d3e4f48ac53',
    messagingSenderId: '766035577642',
    projectId: 'fashionhub-da9d7',
    storageBucket: 'fashionhub-da9d7.appspot.com',
    iosBundleId: 'com.example.fashionhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBypu2Vt8W_KeS3-Ac-GV1hXQh7fC5eZY4',
    appId: '1:766035577642:ios:a5fddb2084f8a2cf48ac53',
    messagingSenderId: '766035577642',
    projectId: 'fashionhub-da9d7',
    storageBucket: 'fashionhub-da9d7.appspot.com',
    iosBundleId: 'com.example.fashionhub.RunnerTests',
  );
}
